// Generated by jextract

package de.jowisoftware.rpgsoundscape.player.audio.frontend.ffmpeg.api;

public final class codec_h {
    public static int AV_ROUND_UP() {
        return (int) 3L;
    }
}


